const COUNTRY_NAMES: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  NL: "Netherlands",
  SE: "Sweden",
  IE: "Ireland",
  IN: "India",
  SG: "Singapore",
  JP: "Japan",
  IL: "Israel",
  CH: "Switzerland",
  ES: "Spain",
  IT: "Italy",
  BR: "Brazil",
  MX: "Mexico",
  KR: "South Korea",
  HK: "Hong Kong",
  NZ: "New Zealand",
  DK: "Denmark",
  NO: "Norway",
  FI: "Finland",
  BE: "Belgium",
  AT: "Austria",
  PL: "Poland",
  PT: "Portugal",
  CZ: "Czech Republic",
  ZA: "South Africa",
  AE: "United Arab Emirates",
  PH: "Philippines",
  CO: "Colombia",
  AR: "Argentina",
  CL: "Chile",
  MY: "Malaysia",
  TH: "Thailand",
  TW: "Taiwan",
  RO: "Romania",
  UA: "Ukraine",
  NG: "Nigeria",
  KE: "Kenya",
  EG: "Egypt",
  WW: "Worldwide Remote",
};

export function getCountryDisplayName(code: string): string {
  return COUNTRY_NAMES[code] || code;
}
