const GENERIC_BUSINESS_ROLE_PATTERNS = [
  /\baccount executive\b/i,
  /\benterprise account executive\b/i,
  /\bcorporate account executive\b/i,
  /\bstrategic account executive\b/i,
  /\bmid[- ]?market account executive\b/i,
  /\baccount manager\b/i,
  /\bcustomer account manager\b/i,
  /\bglobal account manager\b/i,
  /\bcustomer success manager\b/i,
  /\bprincipal customer success\b/i,
  /\bsenior customer success\b/i,
  /\bdirector of customer success\b/i,
  /\bcustomer success (associate|operations|specialist)\b/i,
  /\bmanager,?\s*customer success\b/i,
  /\bcustomer solutions architect\b/i,
  /\bcustomer support specialist\b/i,
  /\bcustomer implementation specialist\b/i,
  /\bbusiness development (representative|manager|director|team lead|lead)\b/i,
  /\bmanager,?\s*business development\b/i,
  /\bsales (representative|manager|director|engineer)\b/i,
  /\bregional sales\b/i,
  /\benterprise sales\b/i,
  /\binside sales\b/i,
  /\bsales development representative\b/i,
  /\bsales enablement\b/i,
  /\bsales strategy\b/i,
  /\bsales operations\b/i,
  /\brevenue operations\b/i,
  /\bpartner development director\b/i,
  /\bstrategic partnerships manager\b/i,
  /\bpartnership(s)?\s*(manager|director)\b/i,
  /\bmarketing (manager|director|programs)\b/i,
  /\bproduct marketing\b/i,
  /\bsolution marketing\b/i,
  /\bmarketing automation\b/i,
  /\bpre[- ]?sales engineering\b/i,
  /\bcontent marketing\b/i,
  /\binbound marketing\b/i,
  /\bcustomer advocacy marketing\b/i,
  /\bdemand gen(eration)?\b/i,
  /\bgrowth marketing\b/i,
  /\bbrand marketing\b/i,
  /\b(svp|vp|head) of marketing\b/i,
  /\bpricing specialist\b/i,
  /\btax (operations|compliance|manager)\b/i,
  /\blegal administrative assistant\b/i,
  /\boffice manager\b/i,
  /\bexecutive assistant\b/i,
  /\bproposal specialist\b/i,
  /\bhead of ai value\b/i,
  /\bgtm (enablement|data)\b/i,
  /\bgtm (manager|team lead|lead|director)\b/i,
  /\bproduct strategy analyst\b/i,
  /\bbenefits program\b/i,
  /\btalent acquisition\b/i,
  /\bsystems specialist,?\s*finance\b/i,
  /\baccounts supervisor\b/i,
  /\bfinancial analyst\b/i,
  /\bfp&?a\b/i,
  /\bdata scientist\b/i,
  /\boperations manager\b/i,
  /\bproject coordinator\b/i,
  /\btrademark.*assistant\b/i,
  /\b(bdr|sdr)\s+(manager|lead|director|team lead)\b/i,
  /\bcloud (data )?(architect|engineer)\b/i,
  /\bcyber\s*security\b/i,
  /\bchief of staff\b/i,
  /\brevenue (enablement|strategy|insights|analyst)\b/i,
  /\bhead of infrastructure\b/i,
  /\binfrastructure (manager|director|lead|engineer)\b/i,
  /\bproduct operations\b/i,
  /\bproject management specialist\b/i,
  /\b(roc|noc|soc) analyst\b/i,
  /\bbusiness intelligence analyst\b/i,
  /\bfield marketing\b/i,
  /\bevent marketing\b/i,
  /\bpre[- ]?sales (architect|engineer|consultant)\b/i,
  /\bpeople partner\b/i,
  /\bglobal campaigns\b/i,
  /\bpricing (analyst|lead)\b/i,
];

const NEGATIVE_AI_SIGNAL_PATTERNS = [
  /does not involve.*technology/i,
  /not suitable for lawyers.*transition/i,
  /not.*legal tech/i,
  /no.*technology component/i,
  /not.*relevant.*legal technology/i,
  /purely.*administrative/i,
  /traditional.*business development/i,
  /no direct connection.*legal/i,
  /general business role/i,
  /not specific to legal/i,
  /standard business function/i,
  /not a legal technology role/i,
  /no legal technology component/i,
  /does not require legal expertise/i,
  /not directly related to legal/i,
  /no.*legal.*component/i,
  /not.*intersection of law and technology/i,
];

export function isGenericBusinessRole(title: string): boolean {
  return GENERIC_BUSINESS_ROLE_PATTERNS.some(pattern => pattern.test(title));
}

export function hasNegativeAiSignal(aiSummary: string | null): boolean {
  if (!aiSummary) return false;
  return NEGATIVE_AI_SIGNAL_PATTERNS.some(pattern => pattern.test(aiSummary));
}
